
baseurl = "https://www.glaciology.net"
title = "Aslak Grinsted"
author = "Aslak Grinsted"
languageCode = "en-us"
defaultContentLanguage = "en-us"

themesDir = "themes"
theme = "hugo-theme-m10c"


[pagination]
  pagerSize = 12

[permalinks]
    post = "/:year/:title"


[menu]
  [[menu.main]]
    identifier = "publication"
    name = "Publications"
    url = "/publication/"
    weight = 1
  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "studentproject"
    name = "Student projects"
    url = "/studentproject/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5
    


[params]
  author = "Aslak Grinsted"
  bio = "Climate scientist and Associate Professor"
  location = "Physics of Ice, Climate, and Earth; Niels Bohr Institute; University of Copenhagen"
  site_description = ""
  avatar = "/avatar.jpg"
  logo = "icon-180x180.png"
  copyright = "Aslak Grinsted"
  description = "Associate Professor at the Niels Bohr Institute, Climate scientist, and dad."
  menu_item_separator = " - "

  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/grinsted"
  [[params.social]]
    icon = "brand-mastodon"
    name = "Mastodon"
    url = "https://fediscience.org/@agrinsted"
  [[params.social]]
    icon = "brand-bluesky"
    name = "Bluesky"
    url = "https://bsky.app/profile/agrinsted.bsky.social"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"

  

