baseurl = "https://www.glaciology.net"
title = "Aslak Grinsted"
author = "Aslak Grinsted"
languageCode = "en-us"

# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
# Define the number of posts per page

paginate = 12
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"

[permalinks]
    post = "/:year/:title"

[params]
    # Tell me who you are
    author = "Aslak Grinsted"
    bio = "Climate Scientist"
    location = "Earth"
    site_description = ""
    avatar = "/avatar.jpg"
    logo = "icon-180x180.png"
    copyright = "Aslak Grinsted"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post","publication"]

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.



[[params.menu]]
    before = false
    label  = "Post"
    link   = "/post/"

[[params.menu]]
    before = false
    label  = "Publications"
    link   = "/publication/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/grinsted"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "grinsted"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "agrinsted"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "aslak.grinsted"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "agrinsted"


[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:ag@glaciology.net"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "//twitter.com/AGrinsted"

[[params.social]]
  icon = "facebook"
  icon_pack = "fa"
  link = "//facebook.com/aslak.grinsted"

[[params.social]]
  icon = "instagram"
  icon_pack = "fa"
  link = "//instagram.com/agrinsted"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "//github.com/grinsted"




# Enable and disable widgets for the right sidebar
[params.widgets]
recent_articles = true
categories = false
tags = false
tag_cloud = false
