baseurl = "https://grinsted.github.io"
title = "Aslak Grinsted"
author = "Aslak Grinsted"
copyright = "Copyright (c) 2016 Aslak Grinsted"
languageCode = "en-us"

# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
# Define the number of posts per page

paginate = 12
footnotereturnlinkcontents = "↩"
theme = "hugo-cryosphere"




[params]
    # Tell me who you are
    author = "Aslak Grinsted"
    bio = "Climate Scientist"
    location = "Earth"
    site_description = ""
    avatar = "/avatar.jpg"
    logo = "icon-180x180.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "Post"
    link   = "/post/"

[[params.menu]]
    before = true
    label  = "Publications"
    link   = "/publication/"


[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:ag@glaciology.net"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "//twitter.com/AGrinsted"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "//github.com/grinsted"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = false
    tag_cloud = true
